#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

# For information on the contents of the container image below, see following Dockerfile:
# https://github.com/gengjiawen/node-build
FROM gengjiawen/node-build:rust

# RUN export https_proxy=http://192.168.1.135:1080

# ENV PATH="/root/.cargo/bin:${PATH}"
# RUN curl  https://sh.rustup.rs -sSf | sh -s --  -y
# RUN apt install sudo net-tools iputils-ping iproute2 -y